import os
from datetime import datetime

from langchain_google_genai import ChatGoogleGenerativeAI


# =========================================================
# CONNECT TO GEMINI
# =========================================================

model = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash"
)


# =========================================================
# FUNCTION TO GET CLEAN TEXT
# =========================================================

def get_text(response):

    if isinstance(response.content, str):
        return response.content

    if isinstance(response.content, list):

        text_parts = []

        for item in response.content:

            if isinstance(item, dict):

                if item.get("type") == "text":
                    text_parts.append(item.get("text", ""))

        return "\n".join(text_parts)

    return str(response.content)


# =========================================================
# SAVE FINAL RESULT TO DESKTOP
# =========================================================

def save_result_to_desktop(result, user_request):

    # Get the user's home folder
    home = os.path.expanduser("~")

    # Windows Desktop location
    desktop = os.path.join(home, "Desktop")

    # If Desktop does not exist, create it
    if not os.path.exists(desktop):
        os.makedirs(desktop)

    # Create date and time
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

    # Create file name
    filename = f"Business_AI_Result_{timestamp}.txt"

    # Complete file path
    filepath = os.path.join(desktop, filename)

    # Write result to file
    with open(filepath, "w", encoding="utf-8") as file:

        file.write("MULTI-AGENT AI BUSINESS AUTOMATION SYSTEM\n")
        file.write("=" * 70 + "\n\n")

        file.write("USER REQUEST\n")
        file.write("=" * 70 + "\n")
        file.write(user_request)
        file.write("\n\n")

        file.write("FINAL RESULT\n")
        file.write("=" * 70 + "\n\n")

        file.write(result)

        file.write("\n\n")
        file.write("=" * 70 + "\n")
        file.write("Generated by Multi-Agent AI System\n")

    return filepath


# =========================================================
# CUSTOMER SUPPORT AGENT
# =========================================================

def customer_support_agent(task):

    prompt = f"""
You are a Customer Support Agent for a business.

Customer request:
{task}

Understand the customer's problem and provide a
professional, helpful and simple response.

If the request needs more information, clearly
mention what information is required.
"""

    response = model.invoke(prompt)

    return get_text(response)


# =========================================================
# REPORT AGENT
# =========================================================

def report_agent(task):

    prompt = f"""
You are a Business Report Agent.

Business request:
{task}

Create a simple and well-structured business report.

Include:

1. Summary
2. Important Information
3. Business Insights
4. Recommendations
5. Conclusion

Use simple professional language.
"""

    response = model.invoke(prompt)

    return get_text(response)


# =========================================================
# TASK MANAGEMENT AGENT
# =========================================================

def task_agent(task):

    prompt = f"""
You are a Business Task Management Agent.

Business request:
{task}

Convert the request into clear business tasks.

For each task provide:

1. Task name
2. Description
3. Priority
4. Suggested action

Organize the tasks clearly.

Use simple professional language.
"""

    response = model.invoke(prompt)

    return get_text(response)


# =========================================================
# MANAGER AGENT
# =========================================================

def manager_agent(task):

    prompt = f"""
You are the Manager Agent of a business automation system.

User request:
{task}

Decide which specialized agent should handle this request.

Choose ONLY one of these:

CUSTOMER_SUPPORT
REPORT
TASK

Return only the agent name.
"""

    response = model.invoke(prompt)

    return get_text(response).strip().upper()


# =========================================================
# MAIN PROGRAM
# =========================================================

print("\n==============================================")
print("   MULTI-AGENT AI BUSINESS AUTOMATION SYSTEM")
print("==============================================")

print("\nThis system has:")
print("1. Manager Agent")
print("2. Customer Support Agent")
print("3. Report Agent")
print("4. Task Management Agent")

print("\nType 'exit' to stop.")


# =========================================================
# MAIN LOOP
# =========================================================

while True:

    user_input = input("\nEnter your business request: ")

    # ---------------------------------------------
    # EXIT PROGRAM
    # ---------------------------------------------

    if user_input.lower() == "exit":

        print("\nAI: Goodbye!")
        break


    # ---------------------------------------------
    # MANAGER AGENT
    # ---------------------------------------------

    print("\nManager Agent is analyzing the request...")

    selected_agent = manager_agent(user_input)

    print("Manager selected:", selected_agent)


    # ---------------------------------------------
    # SPECIALIZED AGENT
    # ---------------------------------------------

    if "CUSTOMER_SUPPORT" in selected_agent:

        print("\nCustomer Support Agent is working...")

        result = customer_support_agent(user_input)


    elif "REPORT" in selected_agent:

        print("\nReport Agent is working...")

        result = report_agent(user_input)


    elif "TASK" in selected_agent:

        print("\nTask Management Agent is working...")

        result = task_agent(user_input)


    else:

        print("\nManager could not identify the correct agent.")
        print("Please try a different business request.")

        continue


    # =================================================
    # DISPLAY FINAL RESULT
    # =================================================

    print("\n==============================================")
    print("              FINAL RESULT")
    print("==============================================")

    print(result)


    # =================================================
    # SAVE RESULT TO DESKTOP
    # =================================================

    try:

        file_path = save_result_to_desktop(
            result,
            user_input
        )

        print("\n==============================================")
        print("           FILE CREATED SUCCESSFULLY")
        print("==============================================")

        print("\nFile saved at:")
        print(file_path)

        print("\nOpen your Desktop to view the file.")

    except Exception as e:

        print("\n==============================================")
        print("             FILE CREATION ERROR")
        print("==============================================")

        print("Error:", e)


    print("\n==============================================")
